/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author miky_
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInventario = new javax.swing.JMenu();
        MenuCategoria = new javax.swing.JMenuItem();
        MenuAgregarInventario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MnuCerrar = new javax.swing.JMenuItem();
        MenuVenta = new javax.swing.JMenu();
        MenuRealizarVenta = new javax.swing.JMenuItem();
        MenuVerVentas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuCategorias = new javax.swing.JMenuItem();
        MenuProductos = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        MenuReporteVentas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Alerta: Producto cerca a su fecha de vencimiento");

        MenuInventario.setText("Archivo");

        MenuCategoria.setText("Inventario");
        MenuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriaActionPerformed(evt);
            }
        });
        MenuInventario.add(MenuCategoria);

        MenuAgregarInventario.setText("Agregar Producto");
        MenuAgregarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgregarInventarioActionPerformed(evt);
            }
        });
        MenuInventario.add(MenuAgregarInventario);
        MenuInventario.add(jSeparator1);

        MnuCerrar.setText("Cerrar");
        MenuInventario.add(MnuCerrar);

        jMenuBar1.add(MenuInventario);

        MenuVenta.setText("Ventas");

        MenuRealizarVenta.setText("Realizar Venta");
        MenuRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRealizarVentaActionPerformed(evt);
            }
        });
        MenuVenta.add(MenuRealizarVenta);

        MenuVerVentas.setText("Ver Ventas");
        MenuVenta.add(MenuVerVentas);

        jMenuBar1.add(MenuVenta);

        jMenu1.setText("Mantenimientos");

        MenuCategorias.setText("Categorias");
        MenuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCategorias);

        MenuProductos.setText("Productos");
        MenuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(MenuProductos);

        jMenuBar1.add(jMenu1);

        MenuReportes.setText("Consultas y Reportes");

        MenuReporteVentas.setText("Reporte Ventas");
        MenuReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuReporteVentasActionPerformed(evt);
            }
        });
        MenuReportes.add(MenuReporteVentas);

        jMenuBar1.add(MenuReportes);

        jMenu5.setText("Ayuda");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriaActionPerformed
        // TODO add your handling code here:
        InventarioFormulario inventario = new InventarioFormulario();
        inventario.setVisible(true);
    }//GEN-LAST:event_MenuCategoriaActionPerformed

    private void MenuAgregarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarInventarioActionPerformed
        Formulario formulario = new Formulario();
        formulario.setLocationRelativeTo(this);
        formulario.setVisible(true);
    }//GEN-LAST:event_MenuAgregarInventarioActionPerformed

    private void MenuRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRealizarVentaActionPerformed
        // TODO add your handling code here:
        TiendaTambo venta = new TiendaTambo();
        venta.setVisible(true);
    }//GEN-LAST:event_MenuRealizarVentaActionPerformed

    private void MenuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCategoriasActionPerformed
        // TODO add your handling code here:
        MantenimientoCategoriaProducto Categorias = new MantenimientoCategoriaProducto();
        Categorias.setVisible(true);
    }//GEN-LAST:event_MenuCategoriasActionPerformed

    private void MenuReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuReporteVentasActionPerformed
        // TODO add your handling code here:
        ReporteVentas reporteVentas = new ReporteVentas();
        reporteVentas.setVisible(true);
    }//GEN-LAST:event_MenuReporteVentasActionPerformed

    private void MenuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductosActionPerformed
        // TODO add your handling code here:
        FormularioProductoAgregar agregarProducto = new FormularioProductoAgregar();
        agregarProducto.setVisible(true);
    }//GEN-LAST:event_MenuProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAgregarInventario;
    private javax.swing.JMenuItem MenuCategoria;
    private javax.swing.JMenuItem MenuCategorias;
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JMenuItem MenuProductos;
    private javax.swing.JMenuItem MenuRealizarVenta;
    private javax.swing.JMenuItem MenuReporteVentas;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu MenuVenta;
    private javax.swing.JMenuItem MenuVerVentas;
    private javax.swing.JMenuItem MnuCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
