/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Beans.Inventario;
import Controller.InventarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eldia
 */
public class InventarioFormulario extends javax.swing.JFrame {

    InventarioController inventarioController = new InventarioController();
    List<Inventario> listInventario = new ArrayList<Inventario>();
    List<String> listaTipoProducto = new ArrayList<String>();
    List<String> listaNombreProducto = new ArrayList<String>();
    /**
     * Creates new form InventarioFormulario
     */
    public InventarioFormulario() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tableInventario.getModel();
        DefaultComboBoxModel tipoProductoModel = new DefaultComboBoxModel();
        
        listInventario = inventarioController.consultaInventario();
        listaTipoProducto = inventarioController.rellenarTipoProducto();
        Object[] rowdata = new Object[5];
        
        for (int i = 0; i < listInventario.size(); i++) {
            rowdata[0] = listInventario.get(i).getLoteProducto();
            rowdata[1] = listInventario.get(i).getTipoProducto();
            rowdata[2] = listInventario.get(i).getNombreProducto();
            rowdata[3] = listInventario.get(i).getFechaVencimientoProducto();
            rowdata[4] = listInventario.get(i).getCantidadProducto();
            modelo.addRow(rowdata);
        }
        tableInventario.setModel(modelo);
        
        int cantidadproductototal=0;
        for (int i = 0; i < listInventario.size(); i++) {
            cantidadproductototal += listInventario.get(i).getCantidadProducto();
        }
        for (int i = 0; i < listaTipoProducto.size(); i++) {
            tipoProductoModel.addElement(listaTipoProducto.get(i));
        }
        txtCantidadProductos.setText(Integer.toString(cantidadproductototal));
        txtValorTotal.setText(Float.toString(inventarioController.calculoValorTotal("", "")));
        cbTipoProducto.setModel(tipoProductoModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbNombreProducto = new javax.swing.JComboBox<>();
        cbTipoProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInventario = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadProductos = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Inventario Actual");

        jLabel2.setText("Por nombre:");

        jLabel3.setText("Por tipo de producto:");

        jLabel4.setText("Busqueda:");

        cbTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoProductoActionPerformed(evt);
            }
        });

        tableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Lote", "Tipo Producto", "Nombre Producto", "Fecha Vencimiento", "Cantidad"
            }
        ));
        tableInventario.setToolTipText("");
        tableInventario.setEnabled(false);
        jScrollPane1.setViewportView(tableInventario);

        jLabel5.setText("Cantidad de productos:");

        txtCantidadProductos.setEditable(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel6.setText("Valor total del inventario S/.");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(268, 268, 268))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidadProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir)
                    .addComponent(jLabel6)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoProductoActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel nombreProductoModel = new DefaultComboBoxModel();

            listaNombreProducto = inventarioController.rellenarNombreProducto(cbTipoProducto.getSelectedItem().toString());
            for (int i = 0; i < listaNombreProducto.size(); i++) {
                nombreProductoModel.addElement(listaNombreProducto.get(i));
            }
            cbNombreProducto.setModel(nombreProductoModel);
        
    }//GEN-LAST:event_cbTipoProductoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Lote");
        modeloTabla.addColumn("Tipo Producto");
        modeloTabla.addColumn("Nombre Producto");
        modeloTabla.addColumn("Fecha Vencimiento");
        modeloTabla.addColumn("Cantidad");
        Object[] rowdataBusqueda = new Object[5];
        
        if (cbTipoProducto.getSelectedIndex() == 0) {
            listInventario = inventarioController.consultaInventario();
        } else {
            listInventario = inventarioController.buscarInventario(cbTipoProducto.getSelectedItem().toString(), cbNombreProducto.getSelectedItem().toString());
        }
        
        for (int i = 0; i < listInventario.size(); i++) {
            rowdataBusqueda[0] = listInventario.get(i).getLoteProducto();
            rowdataBusqueda[1] = listInventario.get(i).getTipoProducto();
            rowdataBusqueda[2] = listInventario.get(i).getNombreProducto();
            rowdataBusqueda[3] = listInventario.get(i).getFechaVencimientoProducto();
            rowdataBusqueda[4] = listInventario.get(i).getCantidadProducto();
            modeloTabla.addRow(rowdataBusqueda);
        }
        tableInventario.setModel(modeloTabla);
        
        int cantidadproductototal=0;
        for (int i = 0; i < listInventario.size(); i++) {
            cantidadproductototal += listInventario.get(i).getCantidadProducto();
        }
        
        txtCantidadProductos.setText(Integer.toString(cantidadproductototal));
        txtValorTotal.setText(Float.toString(inventarioController.calculoValorTotal(cbTipoProducto.getSelectedItem().toString(), cbNombreProducto.getSelectedItem().toString())));
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventarioFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventarioFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventarioFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventarioFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbNombreProducto;
    private javax.swing.JComboBox<String> cbTipoProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInventario;
    private javax.swing.JTextField txtCantidadProductos;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
